### ISSUE TITLE
Came across this error while testing.

### ISSUE THREAD

**Issue by madtomic** [chuushi/PhantomSMP#8]
```java
[14:44:41 ERROR]: Could not pass event PlayerDeathEvent to PhantomSMP v1.1.1
java.lang.NullPointerException: null
        at com.simonorj.mc.phantomsmp.PhantomListener.untarget(PhantomListener.java:95) ~[?:?]
        at com.simonorj.mc.phantomsmp.PhantomListener.onPlayerDeath(PhantomListener.java:160) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor174.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:775) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at net.minecraft.server.v1_14_R1.EntityPlayer.die(EntityPlayer.java:586) ~[paper-1.14.4.jar:git-Paper-10c29e736]        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:117) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at com.zettelnet.levelhearts.storage.PhysicalHealthStorage.setHealth(PhysicalHealthStorage.java:67) ~[?:?]
        at com.zettelnet.levelhearts.storage.sql.SQLHealthStorage.loadPlayer(SQLHealthStorage.java:139) ~[?:?]
        at com.zettelnet.levelhearts.event.LevelHeartsListener.onPlayerJoin(LevelHeartsListener.java:36) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor558.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[paper-1.14.4.jar:git-Paper-10c29e736]        at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[paper-1.14.4.jar:git-Paper-10c29e736]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**Comment by chuushi** [comment]
Hello, thank you for the report.

I need more information.  Did you have any other plugins on the server while testing it?  What is the Paper build #?  What did you do before the error happened?

**Comment by madtomic** [comment]
Latest paperspigot build and this is the only plugin on this test server.

Just die in the game and the error spams.
